waslab04-main/config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    member do
      put 'like'
    end
  end
  root 'tweets#index'
end

waslab04-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

waslab04-main/app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :author, length: {minimum: 4}
  validates :content, length: {in: 4..280}
end

waslab04-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "<h1>It works WASLAB04!</h1>".html_safe
  end
end

waslab04-main/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy like ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        if !session[:created_ids].nil?
          session[:created_ids].push(@tweet.id)
        else
          session[:created_ids] = [@tweet.id]
        end
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else


        s = ""
        @tweet.errors.each do |error|
          if s != ""
          s += " and "
          end
          s += error.full_message
        end



        format.html { redirect_to root_path, alert: s}
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    if (session[:created_ids].nil? || !session[:created_ids].include?(@tweet.id))
      respond_to do |format|
         format.html { redirect_to @tweet, notice: "You are not allowed to delete this tweet." }
         format.json { head :Forbidden }
      end
    else
      @tweet.destroy

      respond_to do |format|
       format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  def like
    @tweet.likes += 1
    @tweet.save
    respond_to do |format|
       format.html { redirect_to root_path }
        format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:author, :content)
    end
end

waslab04-main/app/helpers/application_helper.rb
module ApplicationHelper
end

waslab04-main/app/helpers/tweets_helper.rb
module TweetsHelper
end

waslab04-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waslab04</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="wotbody">
    <%= yield %>
  </body>
</html>

waslab04-main/app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
  <div class="walltweet">
    <table border="0" cellpadding="2">
      <tbody>
        <tr>
          <td><%= form.label :'Your Name:', style: "display: block" %></td>
          <td><%= form.text_field :author %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= form.label :'Your Tweet:', style: "display: block" %></td>
          <td><%= form.text_area :content %></td>
          <td><%= form.submit %></td>
        </tr>
      </tbody>
    </table>
  </div>
<% end %>

waslab04-main/app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>" class="wotitem">
  <div class="likes">
    <span id="showLikes_<%= tweet.id %>" class="numlikes"><%= tweet.likes %></span>
    <br>
    <span class="smallfont">people like this</span>
    <span>
      <br>
      <h3>
        <%
         if (!session[:created_ids].nil? && session[:created_ids].include?(tweet.id))
            %> <%= button_to "destroy", tweet, method: :delete %>
         <% else %>
         <%= button_to 'like', like_tweet_path(tweet), method: :put %>
         <%end%>

      </h3>
    </span>
  </div>
  <div class="item">
    <h4>
      <em><%= tweet.author %></em> @ <%= tweet.created_at.strftime("%H:%M") %>
    </h4>
    <p>
      <%= tweet.content %>
    </p>
  </div>
</div>

waslab04-main/app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

waslab04-main/app/views/tweets/index.html.erb
<h1 class="wottitle">Wall of Tweets</h1>
<br>
  <%= render "form", tweet: Tweet.new %>
<br>

<% if notice.present? or alert.present?%>
<div id="notice" class="wotitem">
<span style="color: green"><%= notice %></span>
<span style="color: red"><%= alert %></span>

</div>
<% end %>

<br>



<br>

<div id="walltweet">
  <% date = nil %>
  <% @tweets.each do |tweet| %>
    <%
    newDate = tweet.created_at.strftime("%A, %B %d, %Y").to_s
    if newDate != date
      date = newDate
    %>
    <h3>...... <%= date %></h3>
    <% end %>

    <%= render tweet %>


  <% end %>
</div>

waslab04-main/app/views/tweets/new.html.erb
<h1 class="wottitle">New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

waslab04-main/app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>